package inventory_system;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

public class Inventory_UI extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_UI
     */
    public Inventory_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxTea = new javax.swing.JCheckBox();
        jTextFieldTea = new javax.swing.JTextField();
        jTextFieldPistachio = new javax.swing.JTextField();
        jCheckBoxBottleWater = new javax.swing.JCheckBox();
        jCheckBoxCoffee = new javax.swing.JCheckBox();
        jCheckBoxIcecream = new javax.swing.JCheckBox();
        jTextFieldCoffee = new javax.swing.JTextField();
        jCheckBoxAlmonds = new javax.swing.JCheckBox();
        jCheckBoxPistachio = new javax.swing.JCheckBox();
        jTextFieldMilkShake = new javax.swing.JTextField();
        jCheckBoxOranges = new javax.swing.JCheckBox();
        jTextFieldBottleWater = new javax.swing.JTextField();
        jCheckBoxChocolate = new javax.swing.JCheckBox();
        jTextFieldOranges = new javax.swing.JTextField();
        jTextFieldChocolate = new javax.swing.JTextField();
        jTextFieldCola = new javax.swing.JTextField();
        jTextFieldIcecream = new javax.swing.JTextField();
        jCheckBoxMilkShake = new javax.swing.JCheckBox();
        jTextFieldAlmonds = new javax.swing.JTextField();
        jCheckBoxCola = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jchkRice = new javax.swing.JCheckBox();
        jTextFieldCorriander = new javax.swing.JTextField();
        jCheckBoxCelery = new javax.swing.JCheckBox();
        jCheckBoxCarrots = new javax.swing.JCheckBox();
        jCheckBoxOnions = new javax.swing.JCheckBox();
        jCheckBoxCorriander = new javax.swing.JCheckBox();
        jTextFieldRice = new javax.swing.JTextField();
        jTextFieldCelery = new javax.swing.JTextField();
        jTextFieldCarrots = new javax.swing.JTextField();
        jTextFieldOnions = new javax.swing.JTextField();
        jCheckBoxGin = new javax.swing.JCheckBox();
        jTextFieldGin = new javax.swing.JTextField();
        jCheckBoxRum = new javax.swing.JCheckBox();
        jTextFieldRum = new javax.swing.JTextField();
        jCheckBoxWine = new javax.swing.JCheckBox();
        jTextFieldWine = new javax.swing.JTextField();
        jCheckBoxVodka = new javax.swing.JCheckBox();
        jTextFieldVodka = new javax.swing.JTextField();
        jCheckBoxWhiskey = new javax.swing.JCheckBox();
        jTextFieldWhiskey = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // TODO 5a: Add WindowListener
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventory Mgt System");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1000, -1));



        // ========================== \\
        /* CHECKBOXES & TEXT FIELDS */
        // ========================== \\

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        // Rice Checkbox
        jchkRice.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jchkRice.setText("Rice");
        jchkRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkRiceActionPerformed(evt);
            }
        });
        jPanel3.add(jchkRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        // Rice Text Field
        jTextFieldRice.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, -1));

        jTextFieldRice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRiceKeyTyped(evt);
            }
        });

        // Celery Checkbox
        jCheckBoxCelery.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxCelery.setText("Celery");
        jCheckBoxCelery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCeleryActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxCelery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        // Celery Text Field
        jTextFieldCelery.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldCelery, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, -1));

        jTextFieldCelery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCeleryKeyTyped(evt);
            }
        });

        // Carrots Checkbox
        jCheckBoxCarrots.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxCarrots.setText("Carrots");
        jCheckBoxCarrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCarrotsActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxCarrots, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        // Carrots Text Field
        jTextFieldCarrots.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldCarrots, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, -1));

        jTextFieldCarrots.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCarrotsKeyTyped(evt);
            }
        });


        // Onions Checkbox
        jCheckBoxOnions.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxOnions.setText("Onions");
        jCheckBoxOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOnionsActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxOnions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        // Onions Text Field
        jTextFieldOnions.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldOnions, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, -1));

        jTextFieldOnions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOnionsKeyTyped(evt);
            }
        });


        // Corriander CheckBox
        jCheckBoxCorriander.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxCorriander.setText("Corriander");
        jCheckBoxCorriander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCorrianderActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxCorriander, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));


        // Corriander Text Field
        jTextFieldCorriander.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldCorriander, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 80, -1));

        jTextFieldCorriander.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCorrianderKeyTyped(evt);
            }
        });


        // Gin Checkbox
        jCheckBoxGin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxGin.setText("Gin");
        jCheckBoxGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGinActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxGin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        // Gin Text Field
        jTextFieldGin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldGin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 80, -1));

        jTextFieldGin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGinKeyTyped(evt);
            }
        });
        

        // Rum Checkbox
        jCheckBoxRum.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxRum.setText("Rum");
        jCheckBoxRum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRumActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxRum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        // Rum Text Field
        jTextFieldRum.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldRum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, -1));

        jTextFieldRum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRumKeyTyped(evt);
            }
        });


        // Wine Checkbox
        jCheckBoxWine.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxWine.setText("Wine");
        jCheckBoxWine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWineActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxWine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        // Wine Text Field
        jTextFieldWine.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldWine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 80, -1));

        jTextFieldWine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWineKeyTyped(evt);
            }
        });


        // Vodka Checkbox
        jCheckBoxVodka.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxVodka.setText("Vodka");
        jCheckBoxVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVodkaActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxVodka, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        // Vodka Text Field
        jTextFieldVodka.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldVodka, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, -1));

        jTextFieldVodka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVodkaKeyTyped(evt);
            }
        });


        // Whiskey Checkbox
        jCheckBoxWhiskey.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxWhiskey.setText("Whiskey");
        jCheckBoxWhiskey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWhiskeyActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxWhiskey, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        // Whiskey Text Field
        jTextFieldWhiskey.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel3.add(jTextFieldWhiskey, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, -1));

        jTextFieldWhiskey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWhiskeyKeyTyped(evt);
            }
        });

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 490, 390));




        // ================================================================================================ //

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Tea Checkbox
        jCheckBoxTea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxTea.setText("Tea");
        jCheckBoxTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTeaActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        // Tea Text Field
        jTextFieldTea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, -1));

        jTextFieldTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTeaKeyTyped(evt);
            }
        });


        // Cola Checkbox
        jCheckBoxCola.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxCola.setText("Cola");
        jCheckBoxCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxColaActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        // Cola Text Field
        jTextFieldCola.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));

        jTextFieldCola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldColaKeyTyped(evt);
            }
        });


        // Coffee Checkbox
        jCheckBoxCoffee.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxCoffee.setText("Coffee");
        jCheckBoxCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoffeeActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        // Coffee Text Field
        jTextFieldCoffee.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 80, -1));

        jTextFieldCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCoffeeKeyTyped(evt);
            }
        });


        // Oranges Checkbox
        jCheckBoxOranges.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxOranges.setText("Oranges");
        jCheckBoxOranges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOrangesActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxOranges, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));


        // Oranges Text Field
        jTextFieldOranges.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldOranges, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, -1));

        jTextFieldOranges.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOrangesKeyTyped(evt);
            }
        });


        // Bottle Water Checkbox
        jCheckBoxBottleWater.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxBottleWater.setText("Bottle Water");
        jCheckBoxBottleWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBottleWaterActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxBottleWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        // Bottle Water Text Field
        jTextFieldBottleWater.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldBottleWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, -1));

        jTextFieldBottleWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBottleWaterKeyTyped(evt);
            }
        });


        // MilkShake Checkbox
        jCheckBoxMilkShake.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxMilkShake.setText("Milk Shake");
        jCheckBoxMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMilkShakeActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMilkShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        // MilkShake Text Field
        jTextFieldMilkShake.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldMilkShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, -1));

        jTextFieldMilkShake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMilkShakeKeyTyped(evt);
            }
        });


        // Icecream Checkbox
        jCheckBoxIcecream.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxIcecream.setText("Icecream");
        jCheckBoxIcecream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIcecreamActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxIcecream, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        // Icecream Text Field
        jTextFieldIcecream.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldIcecream, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, -1));

        jTextFieldIcecream.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIcecreamKeyTyped(evt);
            }
        });


        // Almonds Checkbox
        jCheckBoxAlmonds.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxAlmonds.setText("Almonds");
        jCheckBoxAlmonds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlmondsActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxAlmonds, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));


        // Almonds Text Field
        jTextFieldAlmonds.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldAlmonds, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 80, -1));

        jTextFieldAlmonds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlmondsKeyTyped(evt);
            }
        });


        // Pistachio Checkbox
        jCheckBoxPistachio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxPistachio.setText("Pistachio");
        jCheckBoxPistachio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPistachioActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxPistachio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        // Pistachio Text Field
        jTextFieldPistachio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldPistachio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 80, -1));

        jTextFieldPistachio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPistachioKeyTyped(evt);
            }
        });


        // Chocolate Checkbox
        jCheckBoxChocolate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jCheckBoxChocolate.setText("Chocolate");
        jCheckBoxChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChocolateActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));


        // Chocolate Text Field
        jTextFieldChocolate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 80, -1));

        jTextFieldChocolate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldChocolateKeyTyped(evt);
            }
        });

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 490, 390));


        // =============================================================================== \\

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jTextField6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 110, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Subtotal");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 30));

        jTextField10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 110, -1));

        jTextField12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 110, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Tax");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jbtnReset.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 90, 40));

        jbtnTotal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 90, 40));

        jbtnExit.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 90, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1000, 140));

        pack();
    }// </editor-fold>


    private void jchkRiceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 6a: Enable the Rice Text field when the checkbox is clicked

        if (jchkRice.isSelected()) {
            jTextFieldRice.setEnabled(true);
            jTextFieldRice.setText("");
            jTextFieldRice.requestFocus();
        }
        else {
            jTextFieldRice.setEnabled(false);
            jTextFieldRice.setText("0");
        }
    }

    private void jTextFieldRiceKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxCeleryActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Celery Text field when the checkbox is clicked

        if (jCheckBoxCelery.isSelected()) {
            jTextFieldCelery.setEnabled(true);
            jTextFieldCelery.setText("");
            jTextFieldCelery.requestFocus();
        }
        else {
            jTextFieldCelery.setEnabled(false);
            jTextFieldCelery.setText("0");
        }
    }

    private void jTextFieldCeleryKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxCarrotsActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Carrots Text field when the checkbox is clicked

        if (jCheckBoxCarrots.isSelected()) {
            jTextFieldCarrots.setEnabled(true);
            jTextFieldCarrots.setText("");
            jTextFieldCarrots.requestFocus();
        }
        else {
            jTextFieldCarrots.setEnabled(false);
            jTextFieldCarrots.setText("0");
        }
    }

    private void jTextFieldCarrotsKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }


    private void jCheckBoxOnionsActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Celery Text field when the checkbox is clicked

        if (jCheckBoxOnions.isSelected()) {
            jTextFieldOnions.setEnabled(true);
            jTextFieldOnions.setText("");
            jTextFieldOnions.requestFocus();
        }
        else {
            jTextFieldOnions.setEnabled(false);
            jTextFieldOnions.setText("0");
        }
    }

    private void jTextFieldOnionsKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxCorrianderActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Corriander Text field when the checkbox is clicked

        if (jCheckBoxCorriander.isSelected()) {
            jTextFieldCorriander.setEnabled(true);
            jTextFieldCorriander.setText("");
            jTextFieldCorriander.requestFocus();
        }
        else {
            jTextFieldCorriander.setEnabled(false);
            jTextFieldCorriander.setText("0");
        }
    }

    private void jTextFieldCorrianderKeyTyped(java.awt.event.KeyEvent evt) {
        
        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }


    private void jCheckBoxGinActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Gin Text field when the checkbox is clicked

        if (jCheckBoxGin.isSelected()) {
            jTextFieldGin.setEnabled(true);
            jTextFieldGin.setText("");
            jTextFieldGin.requestFocus();
        }
        else {
            jTextFieldGin.setEnabled(false);
            jTextFieldGin.setText("0");
        }
    }

    private void jTextFieldGinKeyTyped(java.awt.event.KeyEvent evt) {
        
        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxRumActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Rum Text field when the checkbox is clicked

        if (jCheckBoxRum.isSelected()) {
            jTextFieldRum.setEnabled(true);
            jTextFieldRum.setText("");
            jTextFieldRum.requestFocus();
        }
        else {
            jTextFieldRum.setEnabled(false);
            jTextFieldRum.setText("0");
        }
    }

    private void jTextFieldRumKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxWineActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Wine Text field when the checkbox is clicked

        if (jCheckBoxWine.isSelected()) {
            jTextFieldWine.setEnabled(true);
            jTextFieldWine.setText("");
            jTextFieldWine.requestFocus();
        }
        else {
            jTextFieldWine.setEnabled(false);
            jTextFieldWine.setText("0");
        }
    }

    private void jTextFieldWineKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxVodkaActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Wine Text field when the checkbox is clicked

        if (jCheckBoxVodka.isSelected()) {
            jTextFieldVodka.setEnabled(true);
            jTextFieldVodka.setText("");
            jTextFieldVodka.requestFocus();
        }
        else {
            jTextFieldVodka.setEnabled(false);
            jTextFieldVodka.setText("0");
        }
    }

    private void jTextFieldVodkaKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }


    private void jCheckBoxWhiskeyActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Whiskey Text field when the checkbox is clicked

        if (jCheckBoxWhiskey.isSelected()) {
            jTextFieldWhiskey.setEnabled(true);
            jTextFieldWhiskey.setText("");
            jTextFieldWhiskey.requestFocus();
        }
        else {
            jTextFieldWhiskey.setEnabled(false);
            jTextFieldWhiskey.setText("0");
        }
    }

    private void jTextFieldWhiskeyKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }


    private void jCheckBoxTeaActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Tea Text field when the checkbox is clicked

        if (jCheckBoxTea.isSelected()) {
            jTextFieldTea.setEnabled(true);
            jTextFieldTea.setText("");
            jTextFieldTea.requestFocus();
        }
        else {
            jTextFieldTea.setEnabled(false);
            jTextFieldTea.setText("0");
        }
    }

    private void jTextFieldTeaKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxColaActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Cola Text field when the checkbox is clicked

        if (jCheckBoxCola.isSelected()) {
            jTextFieldCola.setEnabled(true);
            jTextFieldCola.setText("");
            jTextFieldCola.requestFocus();
        }
        else {
            jTextFieldCola.setEnabled(false);
            jTextFieldCola.setText("0");
        }
    }

    private void jTextFieldColaKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxCoffeeActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Coffee Text field when the checkbox is clicked

        if (jCheckBoxCoffee.isSelected()) {
            jTextFieldCoffee.setEnabled(true);
            jTextFieldCoffee.setText("");
            jTextFieldCoffee.requestFocus();
        }
        else {
            jTextFieldCoffee.setEnabled(false);
            jTextFieldCoffee.setText("0");
        }
    }

    private void jTextFieldCoffeeKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxOrangesActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Oranges Text field when the checkbox is clicked

        if (jCheckBoxOranges.isSelected()) {
            jTextFieldOranges.setEnabled(true);
            jTextFieldOranges.setText("");
            jTextFieldOranges.requestFocus();
        }
        else {
            jTextFieldOranges.setEnabled(false);
            jTextFieldOranges.setText("0");
        }
    }

    private void jTextFieldOrangesKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxBottleWaterActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Bottle Water Text field when the checkbox is clicked

        if (jCheckBoxBottleWater.isSelected()) {
            jTextFieldBottleWater.setEnabled(true);
            jTextFieldBottleWater.setText("");
            jTextFieldBottleWater.requestFocus();
        }
        else {
            jTextFieldBottleWater.setEnabled(false);
            jTextFieldBottleWater.setText("0");
        }
    }

    private void jTextFieldBottleWaterKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Milk Shake Text field when the checkbox is clicked

        if (jCheckBoxMilkShake.isSelected()) {
            jTextFieldMilkShake.setEnabled(true);
            jTextFieldMilkShake.setText("");
            jTextFieldMilkShake.requestFocus();
        }
        else {
            jTextFieldMilkShake.setEnabled(false);
            jTextFieldMilkShake.setText("0");
        }
    }

    private void jTextFieldMilkShakeKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxIcecreamActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Vanilla Shake Text field when the checkbox is clicked

        if (jCheckBoxIcecream.isSelected()) {
            jTextFieldIcecream.setEnabled(true);
            jTextFieldIcecream.setText("");
            jTextFieldIcecream.requestFocus();
        }
        else {
            jTextFieldIcecream.setEnabled(false);
            jTextFieldIcecream.setText("0");
        }
    }

    private void jTextFieldIcecreamKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }


    private void jCheckBoxAlmondsActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Almonds Text field when the checkbox is clicked

        if (jCheckBoxAlmonds.isSelected()) {
            jTextFieldAlmonds.setEnabled(true);
            jTextFieldAlmonds.setText("");
            jTextFieldAlmonds.requestFocus();
        }
        else {
            jTextFieldAlmonds.setEnabled(false);
            jTextFieldAlmonds.setText("0");
        }
    }

    private void jTextFieldAlmondsKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxPistachioActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Pistachio Text field when the checkbox is clicked

        if (jCheckBoxPistachio.isSelected()) {
            jTextFieldPistachio.setEnabled(true);
            jTextFieldPistachio.setText("");
            jTextFieldPistachio.requestFocus();
        }
        else {
            jTextFieldPistachio.setEnabled(false);
            jTextFieldPistachio.setText("0");
        }
    }

    private void jTextFieldPistachioKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jCheckBoxChocolateActionPerformed(java.awt.event.ActionEvent evt) {
        // Enable the Chocolate Text field when the checkbox is clicked

        if (jCheckBoxChocolate.isSelected()) {
            jTextFieldChocolate.setEnabled(true);
            jTextFieldChocolate.setText("");
            jTextFieldChocolate.requestFocus();
        }
        else {
            jTextFieldChocolate.setEnabled(false);
            jTextFieldChocolate.setText("0");
        }
    }

    private void jTextFieldChocolateKeyTyped(java.awt.event.KeyEvent evt) {

        TaxCalculator noText = new TaxCalculator();
        noText.clearText(evt);
    }

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 4a: Implement Reset Functionality on TextFields
        JTextField clearText = null;
        for (Component component:jPanel3.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)component;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }
        // ==========================================================================
        for (Component component:jPanel2.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)component;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }

        // ==========================================================================
        // TODO 4b: Implement Reset Functionality on CheckBoxes
        JCheckBox clearBox = null;
        for (Component component:jPanel3.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JCheckBox")) {
                clearBox = (JCheckBox) component;
                clearBox.setSelected(false);
            }
        }
        // ==========================================================================
        for (Component component:jPanel2.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JCheckBox")) {
                clearBox = (JCheckBox) component;
                clearBox.setSelected(false);
            }
        }
        // ===========================================================================

    }

    // TODO 5b: Add Reset Code to the formWindowActivated() method
    // This causes text fields to be disabled by default.
    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        JTextField clearText = null;
        for (Component component:jPanel3.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)component;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }
        // ==========================================================================
        for (Component component:jPanel2.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)component;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }

        // ==========================================================================
        JCheckBox clearBox = null;
        for (Component component:jPanel3.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JCheckBox")) {
                clearBox = (JCheckBox) component;
                clearBox.setSelected(false);
            }
        }
        // ==========================================================================
        for (Component component:jPanel2.getComponents()) {
            if (component.getClass().toString().contains("javax.swing.JCheckBox")) {
                clearBox = (JCheckBox) component;
                clearBox.setSelected(false);
            }
        }
        // ===========================================================================
    }

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 7: Button that calculates the total of items in the inventory:

        // Create the required objects
        InventoryPrice item_price = new InventoryPrice();
        TaxCalculator itemTax = new TaxCalculator();

        // Calculation Variables
        double tax, subTotal, grandTotal;

        // We multiply the actual price of the item by what is entered into the item text field
        item_price.Rice = item_price.priceRice * Double.parseDouble(jTextFieldRice.getText());
        item_price.Celery = item_price.priceCelery * Double.parseDouble(jTextFieldCelery.getText());
        item_price.Carrots= item_price.priceCarrots * Double.parseDouble(jTextFieldCarrots.getText());
        item_price.Onions= item_price.priceOnions * Double.parseDouble(jTextFieldOnions.getText());
        item_price.Corriander= item_price.priceCorriander * Double.parseDouble(jTextFieldCorriander.getText());

        item_price.Gin= item_price.priceGin * Double.parseDouble(jTextFieldGin.getText());
        item_price.Rum= item_price.priceRum * Double.parseDouble(jTextFieldRum.getText());
        item_price.Wine= item_price.priceWine * Double.parseDouble(jTextFieldWine.getText());
        item_price.Vodka= item_price.priceVodka * Double.parseDouble(jTextFieldVodka.getText());
        item_price.Whiskey= item_price.priceWhiskey * Double.parseDouble(jTextFieldWhiskey.getText());

        item_price.Tea= item_price.priceTea * Double.parseDouble(jTextFieldTea.getText());
        item_price.Cola= item_price.priceCola * Double.parseDouble(jTextFieldCola.getText());
        item_price.Coffee= item_price.priceCoffee * Double.parseDouble(jTextFieldCoffee.getText());
        item_price.Oranges= item_price.priceOranges * Double.parseDouble(jTextFieldOranges.getText());
        item_price.BottleWater= item_price.priceBottleWater * Double.parseDouble(jTextFieldBottleWater.getText());

        item_price.MilkShake= item_price.priceMilkShake * Double.parseDouble(jTextFieldMilkShake.getText());
        item_price.IceCream= item_price.priceIceCream * Double.parseDouble(jTextFieldIcecream.getText());
        item_price.Almonds= item_price.priceAlmonds * Double.parseDouble(jTextFieldAlmonds.getText());
        item_price.Pistachio= item_price.pricePistachio * Double.parseDouble(jTextFieldPistachio.getText());
        item_price.Chocolate= item_price.priceChocolate * Double.parseDouble(jTextFieldChocolate.getText());

        // Total price minus tax
        subTotal = item_price.getAmount();

        // Calculate the tax of the subTotal amount
        tax = itemTax.calculateTax(subTotal);

        // Calculate the Grand total
        grandTotal = subTotal + tax;


    }

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: 2 - Implement the Quit Functionality
        Quit exit = new Quit();
        exit.quit();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JCheckBox jchkRice;
    private javax.swing.JCheckBox jCheckBoxCorriander;
    private javax.swing.JCheckBox jCheckBoxGin;
    private javax.swing.JCheckBox jCheckBoxRum;
    private javax.swing.JCheckBox jCheckBoxWine;
    private javax.swing.JCheckBox jCheckBoxVodka;
    private javax.swing.JCheckBox jCheckBoxWhiskey;
    private javax.swing.JCheckBox jCheckBoxTea;
    private javax.swing.JCheckBox jCheckBoxMilkShake;
    private javax.swing.JCheckBox jCheckBoxCola;
    private javax.swing.JCheckBox jCheckBoxIcecream;
    private javax.swing.JCheckBox jCheckBoxCoffee;
    private javax.swing.JCheckBox jCheckBoxAlmonds;
    private javax.swing.JCheckBox jCheckBoxOranges;
    private javax.swing.JCheckBox jCheckBoxPistachio;
    private javax.swing.JCheckBox jCheckBoxBottleWater;
    private javax.swing.JCheckBox jCheckBoxChocolate;
    private javax.swing.JCheckBox jCheckBoxCelery;
    private javax.swing.JCheckBox jCheckBoxCarrots;
    private javax.swing.JCheckBox jCheckBoxOnions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldCorriander;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextFieldRice;
    private javax.swing.JTextField jTextFieldCelery;
    private javax.swing.JTextField jTextFieldCarrots;
    private javax.swing.JTextField jTextFieldOnions;
    private javax.swing.JTextField jTextFieldGin;
    private javax.swing.JTextField jTextFieldRum;
    private javax.swing.JTextField jTextFieldWine;
    private javax.swing.JTextField jTextFieldVodka;
    private javax.swing.JTextField jTextFieldWhiskey;
    private javax.swing.JTextField jTextFieldTea;
    private javax.swing.JTextField jTextFieldMilkShake;
    private javax.swing.JTextField jTextFieldCola;
    private javax.swing.JTextField jTextFieldIcecream;
    private javax.swing.JTextField jTextFieldCoffee;
    private javax.swing.JTextField jTextFieldAlmonds;
    private javax.swing.JTextField jTextFieldOranges;
    private javax.swing.JTextField jTextFieldPistachio;
    private javax.swing.JTextField jTextFieldChocolate;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldBottleWater;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    // End of variables declaration
}

